name: ci/cd

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
      - "**.org"

jobs:
  lint-go:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --timeout=15m

  build-docker:
    needs: lint-go
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - run: ko build -B ./
        env:
          KO_DOCKER_REPO: ghcr.io/dearrude
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
